name = "classin-music-api"
main = "worker.js"
compatibility_date = "2026-03-20"


[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "123"
database_id = "bb04f23b-8fa5-4c97-8064-3568e1c06f77"

[ratelimits.simple]
limit = 40
period = 10

[vars]
BASE_URL = "https://cdn.jsdmirror.com/gh/Luo202044/music@a82b77dc4b854926e921f03070c0693d0398358c/"
